# Generated by Django 2.2.4 on 2019-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='chat/'),
        ),
    ]
